const USER_DATA_CATEGORIES = [
  {
    key: 'account',
    label: 'Account',
    description: 'Login identity, profile, account state, and support reference.',
    purpose: 'Run the account, identify the right signed-in user, and give support a safe account reference.',
    classification: 'account',
    sensitivity: 'account',
    exportPath: 'account/profile.json',
    retention: 'Kept while the account exists. Minimal deletion audit records may remain after deletion.',
    retentionPeriod: 'Account lifetime; minimal deletion audit after deletion.',
    retentionDays: null,
    minimization: 'Auth provider records stay outside exports; IScraper stores only profile/support fields it needs.',
    deletion: 'Profile and account rows are deleted during approved account deletion.',
    tables: ['users', 'user_profiles', 'user_admin_states'],
    redaction: 'Exports do not include auth sessions, passwords, or internal admin credentials.',
  },
  {
    key: 'library',
    label: 'Saved library',
    description: 'Saved links, notes, imported saves, collections, smart collections, reminders, and page-archive metadata.',
    purpose: 'Power the user library, search, collections, reminders, and exports.',
    classification: 'private_content',
    sensitivity: 'private_content',
    exportPath: 'library/*.json',
    retention: 'Kept until the user deletes saves or the account is deleted.',
    retentionPeriod: 'Until user deletion or account deletion.',
    retentionDays: null,
    minimization: 'Admin support views use counts and safe event history by default instead of opening saved content.',
    deletion: 'Deleted during approved account deletion.',
    tables: ['saved_items', 'imports', 'collections', 'smart_collections', 'smart_collection_items', 'item_assets', 'item_archives', 'link_health_checks', 'item_reminders'],
    redaction: 'Raw uploaded media files are not included in this phase; asset metadata is exported.',
  },
  {
    key: 'activity',
    label: 'Activity',
    description: 'Search history, result feedback, and support-safe account activity events.',
    purpose: 'Debug user issues, improve search quality, and explain recent account activity without reading saves.',
    classification: 'operational',
    sensitivity: 'behavioral',
    exportPath: 'activity/*.json',
    retention: 'Kept for product quality, support, and account safety until deletion or retention cleanup.',
    retentionPeriod: 'Support timeline 365 days; raw request/security logs 90 days unless needed for abuse or legal reasons.',
    retentionDays: 365,
    minimization: 'Support events use event names, counts, statuses, and safe IDs; emails, tokens, headers, and secrets are redacted.',
    deletion: 'Deleted during approved account deletion unless retained as minimal security audit evidence.',
    tables: ['search_events', 'search_result_feedback', 'user_activity_events', 'lens_search_events'],
    redaction: 'Security hashes, request headers, and tokens are not exported.',
  },
  {
    key: 'ai',
    label: 'AI usage',
    description: 'AI enrichment usage records and non-secret model/provider metadata.',
    purpose: 'Show AI usage, spend credits correctly, and troubleshoot failed enrichment.',
    classification: 'operational',
    sensitivity: 'usage',
    exportPath: 'ai/analysis-usage.json',
    retention: 'Kept for credit accounting and usage visibility.',
    retentionPeriod: 'Account lifetime; billing-linked usage may be retained with billing records.',
    retentionDays: null,
    minimization: 'Stores provider/model/source metadata and item references, not provider API secrets.',
    deletion: 'Deleted with account profile data during approved account deletion.',
    tables: ['analysis_usage_events'],
    redaction: 'Provider API responses and secrets are not exported.',
  },
  {
    key: 'access',
    label: 'Connected access',
    description: 'Provider key metadata, extension tokens, agent tokens, and capture connections.',
    purpose: 'Let the user connect approved tools and revoke access when needed.',
    classification: 'credential',
    sensitivity: 'credential_metadata',
    exportPath: 'access/*.json',
    retention: 'Kept until the user revokes/deletes the connection or the account is deleted.',
    retentionPeriod: 'Until revoked, expired, deleted, or account deletion.',
    retentionDays: null,
    minimization: 'Only metadata and key hints are shown or exported; hashes and encrypted secrets stay server-only.',
    deletion: 'Credentials and tokens are revoked/deleted during approved account deletion.',
    tables: ['user_provider_credentials', 'user_ai_keys', 'extension_tokens', 'capture_connections'],
    redaction: 'Encrypted keys, raw tokens, token hashes, and one-time secrets are never exported.',
  },
  {
    key: 'billing',
    label: 'Credits and billing',
    description: 'Credit balances, credit transactions, purchases, and admin credit adjustments.',
    purpose: 'Maintain credit balances, purchase history, refunds/support, and accounting evidence.',
    classification: 'billing',
    sensitivity: 'billing',
    exportPath: 'billing/credits.json',
    retention: 'Credit records are kept for support and accounting. Completed purchases may be retained as required.',
    retentionPeriod: 'Account lifetime; completed purchase/accounting records up to 7 years where required.',
    retentionDays: 2555,
    minimization: 'Payment card/bank details are not stored by IScraper; external processors keep payment instruments.',
    deletion: 'Non-retained credit rows are deleted during approved account deletion.',
    tables: ['user_credit_accounts', 'credit_transactions', 'credit_purchases', 'admin_credit_adjustments'],
    redaction: 'Payment processor secrets and full payment instrument data are not stored or exported by IScraper.',
  },
  {
    key: 'privacy',
    label: 'Privacy requests',
    description: 'Account deletion request status and export request history.',
    purpose: 'Prove that export/deletion requests were handled and help support complete or retry the workflow.',
    classification: 'audit',
    sensitivity: 'privacy_request',
    exportPath: 'privacy/deletion-request.json',
    retention: 'Deletion audit records may remain in minimal hashed form after deletion.',
    retentionPeriod: 'Export artifacts 7 days; deletion audit hashes may be kept for legal/accountability needs.',
    retentionDays: null,
    minimization: 'Deletion audit keeps minimal status/hash evidence, not private saved content.',
    deletion: 'Active request state is finalized; minimal audit evidence may remain.',
    tables: ['account_deletion_requests', 'account_deletion_steps', 'account_deletion_audit', 'user_data_export_requests', 'user_data_export_steps'],
    redaction: 'Internal deletion hashes and admin-only notes are not exported.',
  },
];

const EXCLUDED_USER_DATA_TABLES = [
  { table: 'account_deletion_audit', reason: 'Retained audit table; user export excludes internal hashes.' },
  { table: 'security_audit_events', reason: 'Server-only security audit table; exports expose user-facing activity without IP/user-agent hashes.' },
  { table: 'item_embeddings', reason: 'Derived vector data is not useful to users and may be large.' },
  { table: 'processing_jobs', reason: 'Operational queue state is not part of user data export.' },
];

const TABLE_DATA_CLASSIFICATIONS = {
  users: 'account',
  user_profiles: 'account',
  user_admin_states: 'account',
  saved_items: 'private_content',
  imports: 'private_content',
  collections: 'private_content',
  smart_collections: 'private_content',
  smart_collection_items: 'private_content',
  item_assets: 'private_content',
  item_analysis: 'private_content',
  item_archives: 'private_content',
  link_health_checks: 'operational',
  item_reminders: 'private_content',
  search_events: 'operational',
  search_result_feedback: 'operational',
  lens_search_events: 'operational',
  user_activity_events: 'audit',
  analysis_usage_events: 'operational',
  user_provider_credentials: 'credential',
  user_ai_keys: 'credential',
  extension_tokens: 'credential',
  capture_connections: 'credential',
  credit_packages: 'public',
  user_credit_accounts: 'billing',
  credit_transactions: 'billing',
  credit_purchases: 'billing',
  admin_credit_adjustments: 'billing',
  account_deletion_requests: 'audit',
  account_deletion_steps: 'audit',
  account_deletion_audit: 'audit',
  user_data_export_requests: 'audit',
  user_data_export_steps: 'audit',
  security_audit_events: 'audit',
  public_feedback: 'public',
  item_embeddings: 'operational',
  processing_jobs: 'operational',
};

const SECRET_LIFECYCLE_RULES = [
  {
    key: 'provider_api_keys',
    label: 'Provider API keys',
    classification: 'credential',
    storage: 'Encrypted at rest with server-side encryption before writing to user_provider_credentials or legacy user_ai_keys.',
    exposure: 'Only provider, purpose, model, status, key hint, and timestamps are shown after creation.',
    lifecycle: 'User can replace, disable, or delete keys; account deletion disables and deletes credential rows.',
    exportRule: 'Never export encrypted keys or raw API keys.',
  },
  {
    key: 'extension_and_agent_tokens',
    label: 'Extension and agent tokens',
    classification: 'credential',
    storage: 'Raw token is shown once; only a token hash, scope list, expiry, last-used time, and revocation time are stored.',
    exposure: 'Frontend and admin screens receive metadata only, never token hashes or raw tokens after creation.',
    lifecycle: 'Tokens are scoped, expirable, revokable, and revoked during account deletion.',
    exportRule: 'Export metadata only; never export token hashes or raw tokens.',
  },
  {
    key: 'capture_connections',
    label: 'Capture and Telegram connections',
    classification: 'credential',
    storage: 'Connection codes/tokens are hashed; public responses expose connection metadata only.',
    exposure: 'Support views should show provider, display name, last-used time, and revoked state without token hashes.',
    lifecycle: 'Connections are revokable by the user and removed during approved deletion.',
    exportRule: 'Export metadata only; never export connection token hashes or one-time codes.',
  },
];

function getUserDataCategories() {
  return USER_DATA_CATEGORIES.map((category) => ({ ...category, tables: [...category.tables] }));
}

function getUserDataMap() {
  return {
    version: 1,
    generatedAt: new Date().toISOString(),
    categories: getUserDataCategories(),
    classifications: TABLE_DATA_CLASSIFICATIONS,
    secretLifecycle: SECRET_LIFECYCLE_RULES,
    excluded: EXCLUDED_USER_DATA_TABLES,
    principles: [
      'Purpose limitation: each category has a product, support, safety, or accounting reason.',
      'Data minimization: exports and dashboards expose useful metadata without secrets or unrelated admin-only notes.',
      'Storage limitation: operational logs are shorter-lived than saved user content and billing/legal evidence.',
      'Security and accountability: sensitive actions are logged with redaction and server-only access.',
    ],
  };
}

function getRetentionRules() {
  return getUserDataCategories().map((category) => ({
    key: category.key,
    label: category.label,
    purpose: category.purpose,
    retention: category.retention,
    retentionPeriod: category.retentionPeriod,
    retentionDays: category.retentionDays,
    minimization: category.minimization,
    deletion: category.deletion,
  }));
}

module.exports = {
  EXCLUDED_USER_DATA_TABLES,
  SECRET_LIFECYCLE_RULES,
  TABLE_DATA_CLASSIFICATIONS,
  USER_DATA_CATEGORIES,
  getUserDataCategories,
  getUserDataMap,
  getRetentionRules,
};
